### ISSUE TITLE
Default solver missing

### ISSUE THREAD

**Issue by ferrolho** [JuliaPolyhedra/QHull.jl#26]
For a polyhedron `p` using `QHull.Library()`, the following line of code returns `Nothing`:
```julia
julia> typeof(Polyhedra.default_solver(p))
Nothing
```
I am not entirely sure this is the root cause of the issue, but look at the following notebook showing `MethodError: no method matching Model(::Nothing)` when a _V_-rep is requested from a _H_-rep:

![Screenshot from 2019-07-11 15-31-21](https://user-images.githubusercontent.com/4166093/61060011-d9523500-a3f1-11e9-8754-0f14a34e30fd.png)

**Comment by blegat** [comment]
This is not well documented and the error message should be clearer. You need to give a solver to QHull.Library, e.g. `QHull.Library(with_optimizer(GLPK.Optimizer))`
